Repository CheHyeonYeong/TinyShop, pull requests merged in 2024-04, with the labels that each got.

#5 👻etc: 사담
  testMJ/tjtlrdl dlTsms .txt
Labels: bug

#12 📝 Customer add annotation
  TinyShop/src/customers/CustomerDAO.java
  TinyShop/src/customers/CustomerServer.java
  out/production/TinyShop/client/Main.class
  out/production/TinyShop/customers/CustomerServer.class
  out/production/TinyShop/foods/FoodsServer.class
  out/production/TinyShop/orders/OrdersServer.class
Labels: documentation

#13 🐛 Customer bug fix
  TinyShop/src/customers/CustomerDAO.java
  TinyShop/src/customers/CustomerServer.java
  out/production/TinyShop/customers/CustomerDAO.class
  out/production/TinyShop/customers/CustomerServer.class
Labels: bug

#22 🐛fix: Orders 전체 수정
  .idea/libraries/mysql_connector_j_8_3_0.xml
  TinyShop/src/orders/OrdersDAO.java
  TinyShop/src/orders/OrdersServer.java
  TinyShop/src/orders/mysql-connector-j-8.3.0.jar
  hs_err_pid19104.log
  out/production/TinyShop/orders/OrdersDAO.class
  out/production/TinyShop/orders/OrdersServer.class
  out/production/TinyShop/orders/mysql-connector-j-8.3.0.jar
Labels: bug, duplicate

#25 ✏️feat: Add login method
  TinyShop/src/client/Client.java
  TinyShop/src/customers/CustomerServer.java
  out/production/TinyShop/client/Client.class
  out/production/TinyShop/customers/CustomerServer.class
Labels: enhancement
